# site settings
title: Edinburgh Anarchist Feminist Bookfair
email: afembook@gmail.com
description: An anarchist feminist bookfair in Edinburgh.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Edinburgh
country: Scotland
phone: (0131) 666 666

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/afembook
instagram_url: https://instagram.com
pinterest_url:
slack_url:
twitter_url: https://twitter.com/afembook

# build settings
markdown: kramdown

sass:
  style: compressed
